# Generated by Django 4.1.4 on 2022-12-15 21:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todolist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('task', models.CharField(max_length=200)),
                ('priority', models.IntegerField(blank=True, default=1, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
